
(cl:in-package :asdf)

(defsystem "backend-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "OrderAction" :depends-on ("_package_OrderAction"))
    (:file "_package_OrderAction" :depends-on ("_package"))
    (:file "OrderActionFeedback" :depends-on ("_package_OrderActionFeedback"))
    (:file "_package_OrderActionFeedback" :depends-on ("_package"))
    (:file "OrderActionGoal" :depends-on ("_package_OrderActionGoal"))
    (:file "_package_OrderActionGoal" :depends-on ("_package"))
    (:file "OrderActionResult" :depends-on ("_package_OrderActionResult"))
    (:file "_package_OrderActionResult" :depends-on ("_package"))
    (:file "OrderFeedback" :depends-on ("_package_OrderFeedback"))
    (:file "_package_OrderFeedback" :depends-on ("_package"))
    (:file "OrderGoal" :depends-on ("_package_OrderGoal"))
    (:file "_package_OrderGoal" :depends-on ("_package"))
    (:file "OrderResult" :depends-on ("_package_OrderResult"))
    (:file "_package_OrderResult" :depends-on ("_package"))
    (:file "PinCodeAction" :depends-on ("_package_PinCodeAction"))
    (:file "_package_PinCodeAction" :depends-on ("_package"))
    (:file "PinCodeActionFeedback" :depends-on ("_package_PinCodeActionFeedback"))
    (:file "_package_PinCodeActionFeedback" :depends-on ("_package"))
    (:file "PinCodeActionGoal" :depends-on ("_package_PinCodeActionGoal"))
    (:file "_package_PinCodeActionGoal" :depends-on ("_package"))
    (:file "PinCodeActionResult" :depends-on ("_package_PinCodeActionResult"))
    (:file "_package_PinCodeActionResult" :depends-on ("_package"))
    (:file "PinCodeFeedback" :depends-on ("_package_PinCodeFeedback"))
    (:file "_package_PinCodeFeedback" :depends-on ("_package"))
    (:file "PinCodeGoal" :depends-on ("_package_PinCodeGoal"))
    (:file "_package_PinCodeGoal" :depends-on ("_package"))
    (:file "PinCodeResult" :depends-on ("_package_PinCodeResult"))
    (:file "_package_PinCodeResult" :depends-on ("_package"))
    (:file "ReviewAction" :depends-on ("_package_ReviewAction"))
    (:file "_package_ReviewAction" :depends-on ("_package"))
    (:file "ReviewActionFeedback" :depends-on ("_package_ReviewActionFeedback"))
    (:file "_package_ReviewActionFeedback" :depends-on ("_package"))
    (:file "ReviewActionGoal" :depends-on ("_package_ReviewActionGoal"))
    (:file "_package_ReviewActionGoal" :depends-on ("_package"))
    (:file "ReviewActionResult" :depends-on ("_package_ReviewActionResult"))
    (:file "_package_ReviewActionResult" :depends-on ("_package"))
    (:file "ReviewFeedback" :depends-on ("_package_ReviewFeedback"))
    (:file "_package_ReviewFeedback" :depends-on ("_package"))
    (:file "ReviewGoal" :depends-on ("_package_ReviewGoal"))
    (:file "_package_ReviewGoal" :depends-on ("_package"))
    (:file "ReviewResult" :depends-on ("_package_ReviewResult"))
    (:file "_package_ReviewResult" :depends-on ("_package"))
  ))