; Auto-generated. Do not edit!


(cl:in-package backend-msg)


;//! \htmlinclude PinCodeGoal.msg.html

(cl:defclass <PinCodeGoal> (roslisp-msg-protocol:ros-message)
  ((pin_code
    :reader pin_code
    :initarg :pin_code
    :type cl:string
    :initform ""))
)

(cl:defclass PinCodeGoal (<PinCodeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PinCodeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PinCodeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name backend-msg:<PinCodeGoal> is deprecated: use backend-msg:PinCodeGoal instead.")))

(cl:ensure-generic-function 'pin_code-val :lambda-list '(m))
(cl:defmethod pin_code-val ((m <PinCodeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader backend-msg:pin_code-val is deprecated.  Use backend-msg:pin_code instead.")
  (pin_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PinCodeGoal>) ostream)
  "Serializes a message object of type '<PinCodeGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'pin_code))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'pin_code))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PinCodeGoal>) istream)
  "Deserializes a message object of type '<PinCodeGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pin_code) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'pin_code) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PinCodeGoal>)))
  "Returns string type for a message object of type '<PinCodeGoal>"
  "backend/PinCodeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PinCodeGoal)))
  "Returns string type for a message object of type 'PinCodeGoal"
  "backend/PinCodeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PinCodeGoal>)))
  "Returns md5sum for a message object of type '<PinCodeGoal>"
  "cc4bcf5aa9a9930d0a06dee449da29e6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PinCodeGoal)))
  "Returns md5sum for a message object of type 'PinCodeGoal"
  "cc4bcf5aa9a9930d0a06dee449da29e6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PinCodeGoal>)))
  "Returns full string definition for message of type '<PinCodeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string pin_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PinCodeGoal)))
  "Returns full string definition for message of type 'PinCodeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string pin_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PinCodeGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'pin_code))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PinCodeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PinCodeGoal
    (cl:cons ':pin_code (pin_code msg))
))
