; Auto-generated. Do not edit!


(cl:in-package backend-msg)


;//! \htmlinclude PinCodeResult.msg.html

(cl:defclass <PinCodeResult> (roslisp-msg-protocol:ros-message)
  ((pin_message
    :reader pin_message
    :initarg :pin_message
    :type cl:string
    :initform ""))
)

(cl:defclass PinCodeResult (<PinCodeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PinCodeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PinCodeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name backend-msg:<PinCodeResult> is deprecated: use backend-msg:PinCodeResult instead.")))

(cl:ensure-generic-function 'pin_message-val :lambda-list '(m))
(cl:defmethod pin_message-val ((m <PinCodeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader backend-msg:pin_message-val is deprecated.  Use backend-msg:pin_message instead.")
  (pin_message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PinCodeResult>) ostream)
  "Serializes a message object of type '<PinCodeResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'pin_message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'pin_message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PinCodeResult>) istream)
  "Deserializes a message object of type '<PinCodeResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'pin_message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'pin_message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PinCodeResult>)))
  "Returns string type for a message object of type '<PinCodeResult>"
  "backend/PinCodeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PinCodeResult)))
  "Returns string type for a message object of type 'PinCodeResult"
  "backend/PinCodeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PinCodeResult>)))
  "Returns md5sum for a message object of type '<PinCodeResult>"
  "33b66bc964db5c960d26bbd3266f83d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PinCodeResult)))
  "Returns md5sum for a message object of type 'PinCodeResult"
  "33b66bc964db5c960d26bbd3266f83d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PinCodeResult>)))
  "Returns full string definition for message of type '<PinCodeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string pin_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PinCodeResult)))
  "Returns full string definition for message of type 'PinCodeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%string pin_message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PinCodeResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'pin_message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PinCodeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PinCodeResult
    (cl:cons ':pin_message (pin_message msg))
))
