; Auto-generated. Do not edit!


(cl:in-package backend-msg)


;//! \htmlinclude ReviewFeedback.msg.html

(cl:defclass <ReviewFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ReviewFeedback (<ReviewFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReviewFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReviewFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name backend-msg:<ReviewFeedback> is deprecated: use backend-msg:ReviewFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReviewFeedback>) ostream)
  "Serializes a message object of type '<ReviewFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReviewFeedback>) istream)
  "Deserializes a message object of type '<ReviewFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReviewFeedback>)))
  "Returns string type for a message object of type '<ReviewFeedback>"
  "backend/ReviewFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReviewFeedback)))
  "Returns string type for a message object of type 'ReviewFeedback"
  "backend/ReviewFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReviewFeedback>)))
  "Returns md5sum for a message object of type '<ReviewFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReviewFeedback)))
  "Returns md5sum for a message object of type 'ReviewFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReviewFeedback>)))
  "Returns full string definition for message of type '<ReviewFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReviewFeedback)))
  "Returns full string definition for message of type 'ReviewFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReviewFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReviewFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ReviewFeedback
))
