; Auto-generated. Do not edit!


(cl:in-package backend-msg)


;//! \htmlinclude ReviewGoal.msg.html

(cl:defclass <ReviewGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ReviewGoal (<ReviewGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReviewGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReviewGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name backend-msg:<ReviewGoal> is deprecated: use backend-msg:ReviewGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReviewGoal>) ostream)
  "Serializes a message object of type '<ReviewGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReviewGoal>) istream)
  "Deserializes a message object of type '<ReviewGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReviewGoal>)))
  "Returns string type for a message object of type '<ReviewGoal>"
  "backend/ReviewGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReviewGoal)))
  "Returns string type for a message object of type 'ReviewGoal"
  "backend/ReviewGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReviewGoal>)))
  "Returns md5sum for a message object of type '<ReviewGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReviewGoal)))
  "Returns md5sum for a message object of type 'ReviewGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReviewGoal>)))
  "Returns full string definition for message of type '<ReviewGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReviewGoal)))
  "Returns full string definition for message of type 'ReviewGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReviewGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReviewGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ReviewGoal
))
