; Auto-generated. Do not edit!


(cl:in-package backend-msg)


;//! \htmlinclude ReviewResult.msg.html

(cl:defclass <ReviewResult> (roslisp-msg-protocol:ros-message)
  ((review
    :reader review
    :initarg :review
    :type cl:integer
    :initform 0))
)

(cl:defclass ReviewResult (<ReviewResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReviewResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReviewResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name backend-msg:<ReviewResult> is deprecated: use backend-msg:ReviewResult instead.")))

(cl:ensure-generic-function 'review-val :lambda-list '(m))
(cl:defmethod review-val ((m <ReviewResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader backend-msg:review-val is deprecated.  Use backend-msg:review instead.")
  (review m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReviewResult>) ostream)
  "Serializes a message object of type '<ReviewResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'review)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReviewResult>) istream)
  "Deserializes a message object of type '<ReviewResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'review)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReviewResult>)))
  "Returns string type for a message object of type '<ReviewResult>"
  "backend/ReviewResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReviewResult)))
  "Returns string type for a message object of type 'ReviewResult"
  "backend/ReviewResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReviewResult>)))
  "Returns md5sum for a message object of type '<ReviewResult>"
  "a18028ab13b7ad75fc3e5bf152f3aa88")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReviewResult)))
  "Returns md5sum for a message object of type 'ReviewResult"
  "a18028ab13b7ad75fc3e5bf152f3aa88")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReviewResult>)))
  "Returns full string definition for message of type '<ReviewResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%byte review~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReviewResult)))
  "Returns full string definition for message of type 'ReviewResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%byte review~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReviewResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReviewResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ReviewResult
    (cl:cons ':review (review msg))
))
