// Auto-generated. Do not edit!

// (in-package backend.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class OrderGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.order_id = null;
      this.pin_code = null;
    }
    else {
      if (initObj.hasOwnProperty('order_id')) {
        this.order_id = initObj.order_id
      }
      else {
        this.order_id = 0;
      }
      if (initObj.hasOwnProperty('pin_code')) {
        this.pin_code = initObj.pin_code
      }
      else {
        this.pin_code = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type OrderGoal
    // Serialize message field [order_id]
    bufferOffset = _serializer.int16(obj.order_id, buffer, bufferOffset);
    // Serialize message field [pin_code]
    bufferOffset = _serializer.string(obj.pin_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type OrderGoal
    let len;
    let data = new OrderGoal(null);
    // Deserialize message field [order_id]
    data.order_id = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [pin_code]
    data.pin_code = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.pin_code.length;
    return length + 6;
  }

  static datatype() {
    // Returns string type for a message object
    return 'backend/OrderGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5a933b66a339c8e24cb0bb060b44273a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    int16 order_id
    string pin_code
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new OrderGoal(null);
    if (msg.order_id !== undefined) {
      resolved.order_id = msg.order_id;
    }
    else {
      resolved.order_id = 0
    }

    if (msg.pin_code !== undefined) {
      resolved.pin_code = msg.pin_code;
    }
    else {
      resolved.pin_code = ''
    }

    return resolved;
    }
};

module.exports = OrderGoal;
