// Auto-generated. Do not edit!

// (in-package backend.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PinCodeGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.pin_code = null;
    }
    else {
      if (initObj.hasOwnProperty('pin_code')) {
        this.pin_code = initObj.pin_code
      }
      else {
        this.pin_code = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PinCodeGoal
    // Serialize message field [pin_code]
    bufferOffset = _serializer.string(obj.pin_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PinCodeGoal
    let len;
    let data = new PinCodeGoal(null);
    // Deserialize message field [pin_code]
    data.pin_code = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.pin_code.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'backend/PinCodeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cc4bcf5aa9a9930d0a06dee449da29e6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string pin_code
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PinCodeGoal(null);
    if (msg.pin_code !== undefined) {
      resolved.pin_code = msg.pin_code;
    }
    else {
      resolved.pin_code = ''
    }

    return resolved;
    }
};

module.exports = PinCodeGoal;
