// Auto-generated. Do not edit!

// (in-package backend.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PinCodeResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.pin_message = null;
    }
    else {
      if (initObj.hasOwnProperty('pin_message')) {
        this.pin_message = initObj.pin_message
      }
      else {
        this.pin_message = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PinCodeResult
    // Serialize message field [pin_message]
    bufferOffset = _serializer.string(obj.pin_message, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PinCodeResult
    let len;
    let data = new PinCodeResult(null);
    // Deserialize message field [pin_message]
    data.pin_message = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.pin_message.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'backend/PinCodeResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '33b66bc964db5c960d26bbd3266f83d6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    string pin_message
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PinCodeResult(null);
    if (msg.pin_message !== undefined) {
      resolved.pin_message = msg.pin_message;
    }
    else {
      resolved.pin_message = ''
    }

    return resolved;
    }
};

module.exports = PinCodeResult;
