// Generated by gencpp from file backend/GetStatusResponse.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_GETSTATUSRESPONSE_H
#define BACKEND_MESSAGE_GETSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace backend
{
template <class ContainerAllocator>
struct GetStatusResponse_
{
  typedef GetStatusResponse_<ContainerAllocator> Type;

  GetStatusResponse_()
    : result(false)
    , error()  {
    }
  GetStatusResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::backend::GetStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::GetStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStatusResponse_

typedef ::backend::GetStatusResponse_<std::allocator<void> > GetStatusResponse;

typedef boost::shared_ptr< ::backend::GetStatusResponse > GetStatusResponsePtr;
typedef boost::shared_ptr< ::backend::GetStatusResponse const> GetStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::GetStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::GetStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace backend

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'backend': ['/home/max/catkin_ws/devel/share/backend/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::backend::GetStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::GetStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::GetStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::GetStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::GetStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::GetStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "961d76fabb30d1ba4f6fcfaa355e1f26";
  }

  static const char* value(const ::backend::GetStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x961d76fabb30d1baULL;
  static const uint64_t static_value2 = 0x4f6fcfaa355e1f26ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/GetStatusResponse";
  }

  static const char* value(const ::backend::GetStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::GetStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
string error\n\
";
  }

  static const char* value(const ::backend::GetStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::GetStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::GetStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::GetStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_GETSTATUSRESPONSE_H
