// Generated by gencpp from file backend/GetStatus.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_GETSTATUS_H
#define BACKEND_MESSAGE_GETSTATUS_H

#include <ros/service_traits.h>


#include <backend/GetStatusRequest.h>
#include <backend/GetStatusResponse.h>


namespace backend
{

struct GetStatus
{

typedef GetStatusRequest Request;
typedef GetStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStatus
} // namespace backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::backend::GetStatus > {
  static const char* value()
  {
    return "14ec8811dcefa7ddf3625f7bbef8560b";
  }

  static const char* value(const ::backend::GetStatus&) { return value(); }
};

template<>
struct DataType< ::backend::GetStatus > {
  static const char* value()
  {
    return "backend/GetStatus";
  }

  static const char* value(const ::backend::GetStatus&) { return value(); }
};


// service_traits::MD5Sum< ::backend::GetStatusRequest> should match 
// service_traits::MD5Sum< ::backend::GetStatus > 
template<>
struct MD5Sum< ::backend::GetStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::backend::GetStatus >::value();
  }
  static const char* value(const ::backend::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::backend::GetStatusRequest> should match 
// service_traits::DataType< ::backend::GetStatus > 
template<>
struct DataType< ::backend::GetStatusRequest>
{
  static const char* value()
  {
    return DataType< ::backend::GetStatus >::value();
  }
  static const char* value(const ::backend::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::backend::GetStatusResponse> should match 
// service_traits::MD5Sum< ::backend::GetStatus > 
template<>
struct MD5Sum< ::backend::GetStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::backend::GetStatus >::value();
  }
  static const char* value(const ::backend::GetStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::backend::GetStatusResponse> should match 
// service_traits::DataType< ::backend::GetStatus > 
template<>
struct DataType< ::backend::GetStatusResponse>
{
  static const char* value()
  {
    return DataType< ::backend::GetStatus >::value();
  }
  static const char* value(const ::backend::GetStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BACKEND_MESSAGE_GETSTATUS_H
