// Generated by gencpp from file backend/OrderStatusRequest.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_ORDERSTATUSREQUEST_H
#define BACKEND_MESSAGE_ORDERSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace backend
{
template <class ContainerAllocator>
struct OrderStatusRequest_
{
  typedef OrderStatusRequest_<ContainerAllocator> Type;

  OrderStatusRequest_()
    : order_id(0)  {
    }
  OrderStatusRequest_(const ContainerAllocator& _alloc)
    : order_id(0)  {
  (void)_alloc;
    }



   typedef int16_t _order_id_type;
  _order_id_type order_id;





  typedef boost::shared_ptr< ::backend::OrderStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::OrderStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OrderStatusRequest_

typedef ::backend::OrderStatusRequest_<std::allocator<void> > OrderStatusRequest;

typedef boost::shared_ptr< ::backend::OrderStatusRequest > OrderStatusRequestPtr;
typedef boost::shared_ptr< ::backend::OrderStatusRequest const> OrderStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::OrderStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::OrderStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace backend

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'backend': ['/home/max/catkin_ws/devel/share/backend/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::backend::OrderStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::OrderStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::OrderStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::OrderStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::OrderStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::OrderStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::OrderStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "379beef79dd85692d7c86500ee7cd805";
  }

  static const char* value(const ::backend::OrderStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x379beef79dd85692ULL;
  static const uint64_t static_value2 = 0xd7c86500ee7cd805ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::OrderStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/OrderStatusRequest";
  }

  static const char* value(const ::backend::OrderStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::OrderStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 order_id\n\
";
  }

  static const char* value(const ::backend::OrderStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::OrderStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrderStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::OrderStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::OrderStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "order_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.order_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_ORDERSTATUSREQUEST_H
