// Generated by gencpp from file backend/OrderStatus.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_ORDERSTATUS_H
#define BACKEND_MESSAGE_ORDERSTATUS_H

#include <ros/service_traits.h>


#include <backend/OrderStatusRequest.h>
#include <backend/OrderStatusResponse.h>


namespace backend
{

struct OrderStatus
{

typedef OrderStatusRequest Request;
typedef OrderStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrderStatus
} // namespace backend


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::backend::OrderStatus > {
  static const char* value()
  {
    return "954d97139ffd0d17e83f4320bddc89c8";
  }

  static const char* value(const ::backend::OrderStatus&) { return value(); }
};

template<>
struct DataType< ::backend::OrderStatus > {
  static const char* value()
  {
    return "backend/OrderStatus";
  }

  static const char* value(const ::backend::OrderStatus&) { return value(); }
};


// service_traits::MD5Sum< ::backend::OrderStatusRequest> should match 
// service_traits::MD5Sum< ::backend::OrderStatus > 
template<>
struct MD5Sum< ::backend::OrderStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::backend::OrderStatus >::value();
  }
  static const char* value(const ::backend::OrderStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::backend::OrderStatusRequest> should match 
// service_traits::DataType< ::backend::OrderStatus > 
template<>
struct DataType< ::backend::OrderStatusRequest>
{
  static const char* value()
  {
    return DataType< ::backend::OrderStatus >::value();
  }
  static const char* value(const ::backend::OrderStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::backend::OrderStatusResponse> should match 
// service_traits::MD5Sum< ::backend::OrderStatus > 
template<>
struct MD5Sum< ::backend::OrderStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::backend::OrderStatus >::value();
  }
  static const char* value(const ::backend::OrderStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::backend::OrderStatusResponse> should match 
// service_traits::DataType< ::backend::OrderStatus > 
template<>
struct DataType< ::backend::OrderStatusResponse>
{
  static const char* value()
  {
    return DataType< ::backend::OrderStatus >::value();
  }
  static const char* value(const ::backend::OrderStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BACKEND_MESSAGE_ORDERSTATUS_H
