// Generated by gencpp from file backend/PinCodeResult.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_PINCODERESULT_H
#define BACKEND_MESSAGE_PINCODERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace backend
{
template <class ContainerAllocator>
struct PinCodeResult_
{
  typedef PinCodeResult_<ContainerAllocator> Type;

  PinCodeResult_()
    : pin_message()  {
    }
  PinCodeResult_(const ContainerAllocator& _alloc)
    : pin_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pin_message_type;
  _pin_message_type pin_message;





  typedef boost::shared_ptr< ::backend::PinCodeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::PinCodeResult_<ContainerAllocator> const> ConstPtr;

}; // struct PinCodeResult_

typedef ::backend::PinCodeResult_<std::allocator<void> > PinCodeResult;

typedef boost::shared_ptr< ::backend::PinCodeResult > PinCodeResultPtr;
typedef boost::shared_ptr< ::backend::PinCodeResult const> PinCodeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::PinCodeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::PinCodeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace backend

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'backend': ['/home/max/catkin_ws/devel/share/backend/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::backend::PinCodeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::PinCodeResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::PinCodeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::PinCodeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::PinCodeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::PinCodeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::PinCodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33b66bc964db5c960d26bbd3266f83d6";
  }

  static const char* value(const ::backend::PinCodeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33b66bc964db5c96ULL;
  static const uint64_t static_value2 = 0x0d26bbd3266f83d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::PinCodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/PinCodeResult";
  }

  static const char* value(const ::backend::PinCodeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::PinCodeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result\n\
string pin_message\n\
";
  }

  static const char* value(const ::backend::PinCodeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::PinCodeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PinCodeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::PinCodeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::PinCodeResult_<ContainerAllocator>& v)
  {
    s << indent << "pin_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pin_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_PINCODERESULT_H
