// Generated by gencpp from file backend/ReviewResult.msg
// DO NOT EDIT!


#ifndef BACKEND_MESSAGE_REVIEWRESULT_H
#define BACKEND_MESSAGE_REVIEWRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace backend
{
template <class ContainerAllocator>
struct ReviewResult_
{
  typedef ReviewResult_<ContainerAllocator> Type;

  ReviewResult_()
    : review(0)  {
    }
  ReviewResult_(const ContainerAllocator& _alloc)
    : review(0)  {
  (void)_alloc;
    }



   typedef int8_t _review_type;
  _review_type review;





  typedef boost::shared_ptr< ::backend::ReviewResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::backend::ReviewResult_<ContainerAllocator> const> ConstPtr;

}; // struct ReviewResult_

typedef ::backend::ReviewResult_<std::allocator<void> > ReviewResult;

typedef boost::shared_ptr< ::backend::ReviewResult > ReviewResultPtr;
typedef boost::shared_ptr< ::backend::ReviewResult const> ReviewResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::backend::ReviewResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::backend::ReviewResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace backend

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'backend': ['/home/max/catkin_ws/devel/share/backend/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::backend::ReviewResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::backend::ReviewResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::ReviewResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::backend::ReviewResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::ReviewResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::backend::ReviewResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::backend::ReviewResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a18028ab13b7ad75fc3e5bf152f3aa88";
  }

  static const char* value(const ::backend::ReviewResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa18028ab13b7ad75ULL;
  static const uint64_t static_value2 = 0xfc3e5bf152f3aa88ULL;
};

template<class ContainerAllocator>
struct DataType< ::backend::ReviewResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "backend/ReviewResult";
  }

  static const char* value(const ::backend::ReviewResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::backend::ReviewResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result\n\
byte review\n\
";
  }

  static const char* value(const ::backend::ReviewResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::backend::ReviewResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.review);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReviewResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::backend::ReviewResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::backend::ReviewResult_<ContainerAllocator>& v)
  {
    s << indent << "review: ";
    Printer<int8_t>::stream(s, indent + "  ", v.review);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BACKEND_MESSAGE_REVIEWRESULT_H
