(cl:defpackage backend-srv
  (:use )
  (:export
   "GETSTATUS"
   "<GETSTATUS-REQUEST>"
   "GETSTATUS-REQUEST"
   "<GETSTATUS-RESPONSE>"
   "GETSTATUS-RESPONSE"
   "ORDERSTATUS"
   "<ORDERSTATUS-REQUEST>"
   "ORDERSTATUS-REQUEST"
   "<ORDERSTATUS-RESPONSE>"
   "ORDERSTATUS-RESPONSE"
   "SCREEN"
   "<SCREEN-REQUEST>"
   "SCREEN-REQUEST"
   "<SCREEN-RESPONSE>"
   "SCREEN-RESPONSE"
  ))

