// Generated by gencpp from file rospy_message_converter/Uint8Array3TestMessage.msg
// DO NOT EDIT!


#ifndef ROSPY_MESSAGE_CONVERTER_MESSAGE_UINT8ARRAY3TESTMESSAGE_H
#define ROSPY_MESSAGE_CONVERTER_MESSAGE_UINT8ARRAY3TESTMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rospy_message_converter
{
template <class ContainerAllocator>
struct Uint8Array3TestMessage_
{
  typedef Uint8Array3TestMessage_<ContainerAllocator> Type;

  Uint8Array3TestMessage_()
    : data()  {
      data.assign(0);
  }
  Uint8Array3TestMessage_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<uint8_t, 3>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> const> ConstPtr;

}; // struct Uint8Array3TestMessage_

typedef ::rospy_message_converter::Uint8Array3TestMessage_<std::allocator<void> > Uint8Array3TestMessage;

typedef boost::shared_ptr< ::rospy_message_converter::Uint8Array3TestMessage > Uint8Array3TestMessagePtr;
typedef boost::shared_ptr< ::rospy_message_converter::Uint8Array3TestMessage const> Uint8Array3TestMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rospy_message_converter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rospy_message_converter': ['/home/max/catkin_ws/src/rospy_message_converter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0aff379edf54a041a83af067122e7bc6";
  }

  static const char* value(const ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0aff379edf54a041ULL;
  static const uint64_t static_value2 = 0xa83af067122e7bc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rospy_message_converter/Uint8Array3TestMessage";
  }

  static const char* value(const ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Fixed size uint8 array for testing purposes\n\
uint8[3] data\n\
";
  }

  static const char* value(const ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Uint8Array3TestMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rospy_message_converter::Uint8Array3TestMessage_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPY_MESSAGE_CONVERTER_MESSAGE_UINT8ARRAY3TESTMESSAGE_H
